// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQ0gOxBegUdH9Jr1zvu6Ex5EYtVteM8g',
    appId: '1:495544191021:web:50fed44a9146866b4050a4',
    messagingSenderId: '495544191021',
    projectId: 'gymtrack-6ccad',
    authDomain: 'gymtrack-6ccad.firebaseapp.com',
    storageBucket: 'gymtrack-6ccad.firebasestorage.app',
    measurementId: 'G-4QXEEJDF3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAv_k5RpVJR0loDRY_97wisXsCxX9VmY',
    appId: '1:495544191021:android:bfcb36882fe9bea54050a4',
    messagingSenderId: '495544191021',
    projectId: 'gymtrack-6ccad',
    storageBucket: 'gymtrack-6ccad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55QEUNla6hatmB4Id4ELqZoVJ7DrVcJc',
    appId: '1:495544191021:ios:b5a6a6fd5ab22dc64050a4',
    messagingSenderId: '495544191021',
    projectId: 'gymtrack-6ccad',
    storageBucket: 'gymtrack-6ccad.firebasestorage.app',
    iosBundleId: 'com.example.gymTrack',
  );
}
